# Discovery of peers method used: bootnodes

services:

  # bootnode
  node-a:
    image: hyperledger/besu:latest
    container_name: node-a
    hostname: node-a
    # restart: on-failure
    volumes:
      - ./data/1:/var/lib/besu
      - ./config/nodes/1/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/1/key:/var/lib/besu/key
      - ./config/nodes/1/key.pub:/var/lib/besu/key.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.3
    ports:
      - "8545:8545" # RPC = 8545 + 0: 8545 (does not change)
      - "9545:9545" # Metrics = 9545 + 0: 9545 (does not change)
      - "30303:30303" # P2P = 30303 + 0: 30303 (does not change)
    command:
      [
        # Must parameters
        "--identity=node-a",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",
        "--sync-min-peers=1",
        

        # RPC
        "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT,WEB3,PRIV",
        "--rpc-http-enabled",
        "--rpc-ws-enabled",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-port=8545",

        # Metrics
        "--metrics-enabled=true",
        "--metrics-port=9545",

        # p2p
        "--p2p-port=30303",

        # On-chain permissions
        "--permissions-nodes-contract-version=2",
        "--permissions-nodes-contract-enabled",
        "--permissions-accounts-contract-enabled",
        "--permissions-nodes-contract-address=0x0000000000000000000000000000000000009999",
        "--permissions-accounts-contract-address=0x0000000000000000000000000000000000008888",

        # Bootnodes
        "--bootnodes=enode://9299664c95fd8817917d39a655a38657859eee99e84db0157cbbfb169c0bb1a0c0f30ee2358f5fd9a0526b0657079dcc55527ed653b93d8c38d6fbc98c9724fc@172.20.0.4:30303",
      ]

  node-b:
    image: hyperledger/besu:latest
    container_name: node-b
    hostname: node-b
    volumes:
      - ./data/2:/var/lib/besu
      - ./config/nodes/2/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/2/key:/var/lib/besu/key
      - ./config/nodes/2/key.pub:/var/lib/besu/key.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.4
    ports:
      - "8546:8545"
      - "9546:9545"
      - "30304:30303"
    command:
      [
        # Must parameters
        "--identity=node-a",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",
        "--sync-min-peers=1",
        

        # RPC
        "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT,WEB3,PRIV",
        "--rpc-http-enabled",
        "--rpc-ws-enabled",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-port=8545",

        # Metrics
        "--metrics-enabled=true",
        "--metrics-port=9545",

        # p2p
        "--p2p-port=30303",

        # On-chain permissions
        "--permissions-nodes-contract-version=2",
        "--permissions-nodes-contract-enabled",
        "--permissions-accounts-contract-enabled",
        "--permissions-nodes-contract-address=0x0000000000000000000000000000000000009999",
        "--permissions-accounts-contract-address=0x0000000000000000000000000000000000008888",

        # Bootnoodes
        "--bootnodes=enode://69e84b9c135d789b637ba454fdcf7c348b3fcee0713e248c1e3edcc652088563ae5a4fd0698f7f796b875bd8008c9197022e7c15c3680e8b7cb7ec68f8b33dfa@172.20.0.3:30303",

      ]

  node-c:
    image: hyperledger/besu:latest
    container_name: node-c
    hostname: node-c
    volumes:
      - ./data/3:/var/lib/besu
      - ./config/nodes/3/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/3/key:/var/lib/besu/key
      - ./config/nodes/3/key.pub:/var/lib/besu/key.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.5
    ports:
      - "8547:8545"
      - "9547:9545"
      - "30305:30303"
    command:
      [
        # Must parameters
        "--identity=node-a",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",
        "--sync-min-peers=1",
        

        # RPC
        "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT,WEB3,PRIV",
        "--rpc-http-enabled",
        "--rpc-ws-enabled",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-port=8545",

        # Metrics
        "--metrics-enabled=true",
        "--metrics-port=9545",

        # p2p
        "--p2p-port=30303",

        # On-chain permissions
        "--permissions-nodes-contract-version=2",
        "--permissions-nodes-contract-enabled",
        "--permissions-accounts-contract-enabled",
        "--permissions-nodes-contract-address=0x0000000000000000000000000000000000009999",
        "--permissions-accounts-contract-address=0x0000000000000000000000000000000000008888",

        # Bootnoodes
        "--bootnodes=enode://69e84b9c135d789b637ba454fdcf7c348b3fcee0713e248c1e3edcc652088563ae5a4fd0698f7f796b875bd8008c9197022e7c15c3680e8b7cb7ec68f8b33dfa@172.20.0.3:30303,enode://18808d740470a14ca76548ca37643e69806f562b36453c4f72e36bc9f73e01bce9de5e924f4fd3a2540f748bd9afe198f9076ee9eebc200bb70e928d6cf43d20@172.20.0.4:30303",
      ]

  node-d:
    image: hyperledger/besu:latest
    container_name: node-d
    hostname: node-d
    volumes:
      - ./data/4:/var/lib/besu
      - ./config/nodes/4/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/4/key:/var/lib/besu/key
      - ./config/nodes/4/key.pub:/var/lib/besu/key.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.6
    ports:
      - "8548:8545"
      - "9548:9545"
      - "30306:30303"
    command:
      [
        # Must parameters
        "--identity=node-a",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",
        "--sync-min-peers=1",
        

        # RPC
        "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT,WEB3,PRIV",
        "--rpc-http-enabled",
        "--rpc-ws-enabled",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-port=8545",

        # Metrics
        "--metrics-enabled=true",
        "--metrics-port=9545",

        # p2p
        "--p2p-port=30303",

        # On-chain permissions
        "--permissions-nodes-contract-version=2",
        "--permissions-nodes-contract-enabled",
        "--permissions-accounts-contract-enabled",
        "--permissions-nodes-contract-address=0x0000000000000000000000000000000000009999",
        "--permissions-accounts-contract-address=0x0000000000000000000000000000000000008888",

        # Bootnoodes
        "--bootnodes=enode://69e84b9c135d789b637ba454fdcf7c348b3fcee0713e248c1e3edcc652088563ae5a4fd0698f7f796b875bd8008c9197022e7c15c3680e8b7cb7ec68f8b33dfa@172.20.0.3:30303,enode://18808d740470a14ca76548ca37643e69806f562b36453c4f72e36bc9f73e01bce9de5e924f4fd3a2540f748bd9afe198f9076ee9eebc200bb70e928d6cf43d20@172.20.0.4:30303",
      ]

networks:
  besu-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
