# Discovery of peers method used: bootnodes

services:

  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      besu-network:
        ipv4_address: 172.20.0.4
    depends_on:
      - node-a

  # bootnode
  node-a:
    image: hyperledger/besu:latest
    container_name: node-a
    hostname: node-a
    # restart: on-failure
    volumes:
      - ./data/1:/var/lib/besu
      - ./config/nodes/1/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/1/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/1/key:/var/lib/besu/key
    networks:
      besu-network:
        ipv4_address: 172.20.0.2 # 172.20.0.2 + 0
    ports:
      - "8545:8545" # RPC = 8545 + 0: 8545 (does not change)
      - "9545:9545" # Metrics = 9545 + 0: 9545 (does not change)
      - "30303:30303" # P2P = 30303 + 0: 30303 (does not change)
    command:
      [
        # besu --data-path=local/1/ --genesis-file=local/genesis.json --miner-enabled --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73 --rpc-http-enabled --host-whitelist="*" --rpc-http-cors-origins="*" --rpc-http-port=8545

        # Must parameters
        "--identity=node-a",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",

        # Miner
        "--miner-enabled",
        "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",

        # Permissioned network parameters
        "--permissions-nodes-config-file-enabled",
        "--permissions-accounts-config-file-enabled",

        # RPC protocol for requests
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",

        # Services
        "--rpc-http-enabled",
        "--metrics-enabled=true",

        # Ports
        "--rpc-http-port=8545",
        "--p2p-port=30303",
        "--metrics-port=9545",

        # Peers
        "--sync-min-peers=3",
      ]

  node-b:
    image: hyperledger/besu:latest
    container_name: node-b
    hostname: node-b
    volumes:
      - ./data/2:/var/lib/besu
      - ./config/nodes/2/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/2/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/2/key:/var/lib/besu/key
    networks:
      besu-network:
        ipv4_address:  172.20.0.3 # 172.20.0.2 + 1
    ports:
      - "8546:8545" # RPC = 8545 + 1: 8545 (does not change)
      - "9546:9545" # Metrics = 9545 + 1: 9545 (does not change)
      - "30304:30303" # P2P = 30303 + 1: 30303 (does not change)
    command:
      [
        # besu --data-path=local/2/ --genesis-file=local/genesis.json --bootnodes=enode://4730f6cc03c889ba161a7172f2839d7c7df52e47eb6ba8464680c13fe6a3cab392a51a7703091ee4effc956d6c537b7d45067cbf349bed5ce7474b8547151260@127.0.0.1:30303 --p2p-port=30304

        # Node b enode: enode://9299664c95fd8817917d39a655a38657859eee99e84db0157cbbfb169c0bb1a0c0f30ee2358f5fd9a0526b0657079dcc55527ed653b93d8c38d6fbc98c9724fc@172.20.0.3:30303

        # Must parameters
        "--identity=node-b",
        "--data-path=/var/lib/besu",
        "--genesis-file=/var/lib/besu/genesis.json",

        # Bootnoodes
        "--bootnodes=enode://4730f6cc03c889ba161a7172f2839d7c7df52e47eb6ba8464680c13fe6a3cab392a51a7703091ee4effc956d6c537b7d45067cbf349bed5ce7474b8547151260@172.20.0.2:30303",

        # Ports
        "--p2p-port=30303",
        "--metrics-port=9545",
        "--rpc-http-port=8545",

        # Permissioned network parameters
        "--permissions-nodes-config-file-enabled",
        "--permissions-accounts-config-file-enabled",

        # Peers
        "--sync-min-peers=3",

        # Services
        "--rpc-http-enabled",
        "--metrics-enabled=true",

        # RPC protocol for requests
        "--host-whitelist=\"*\"",
        "--rpc-http-cors-origins=\"*\"",
      ]

networks:
  besu-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
