# Discovery of peers method used: bootnodes

services:
  besu-node1:
    image: hyperledger/besu:latest
    restart: on-failure
    container_name: besu-node1
    volumes:
      - ./data/besu-node1:/var/lib/besu
      - ./config/nodes/1/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/1/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/1/key:/var/lib/besu/key
    networks:
      - besu-network
    ports:
      - "8545:8545"
      - "9545:9545"
      - "30303:30303"
    command: [

      # Must parameters
      "--identity=node1",
      "--data-path=/var/lib/besu",
      "--genesis-file=/var/lib/besu/genesis.json",

      # P2P
      "--p2p-port=30303", # 30303 + 0

      # Permissioned network parameters
      "--permissions-nodes-config-file-enabled",
      "--permissions-accounts-config-file-enabled",

      # RPC protocol for requests
      "--rpc-http-enabled",
      "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT",
      "--host-allowlist=\"*\"",
      "--rpc-http-cors-origins=\"*\"",
      "--rpc-http-port=8545", # 8545 + 0

      # Metrics
      "--metrics-enabled=true",
      "--metrics-port=9545", # 9545 + 0
      "--metrics-host=0.0.0.0",

    ]

  besu-node2:
    image: hyperledger/besu:latest
    restart: on-failure
    container_name: besu-node2
    volumes:
      - ./data/besu-node2:/var/lib/besu
      - ./config/nodes/2/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/2/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/2/key:/var/lib/besu/key
    networks:
      - besu-network
    ports:
      - "8546:8546"
      - "9546:9546"
      - "30304:30304"
    command: [
      
      # Must parameters
      "--identity=besu-node2",
      "--data-path=/var/lib/besu",
      "--genesis-file=/var/lib/besu/genesis.json",

      # P2P
      "--p2p-port=30304", # 30303 + 1

      # Permissioned network parameters
      "--permissions-nodes-config-file-enabled",
      "--permissions-accounts-config-file-enabled",

      # RPC protocol for requests
      "--rpc-http-enabled",
      "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT",
      "--host-allowlist=\"*\"",
      "--rpc-http-cors-origins=\"*\"",
      "--rpc-http-port=8546", # 8545 + 1

      # Metrics
      "--metrics-enabled=true",
      "--metrics-port=9546", # 9545 + 1
      "--metrics-host=0.0.0.0", # localhost

    ]

  besu-node3:
    image: hyperledger/besu:latest
    restart: on-failure
    container_name: besu-node3
    volumes:
      - ./data/besu-node3:/var/lib/besu
      - ./config/nodes/3/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/3/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/3/key:/var/lib/besu/key
    networks:
      - besu-network
    ports:
      - "8547:8547"
      - "9547:9547"
      - "30305:30305"
    command: [
      
      # Must parameters
      "--identity=besu-node3",
      "--data-path=/var/lib/besu",
      "--genesis-file=/var/lib/besu/genesis.json",

      # P2P
      "--p2p-port=30305", # 30303 + 2

      # Permissioned network parameters
      "--permissions-nodes-config-file-enabled",
      "--permissions-accounts-config-file-enabled",

      # RPC protocol for requests
      "--rpc-http-enabled",
      "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT",
      "--host-allowlist=\"*\"",
      "--rpc-http-cors-origins=\"*\"",
      "--rpc-http-port=8547", # 8545 + 2

      # Metrics
      "--metrics-enabled=true",
      "--metrics-port=9547", # 9545 + 2
      "--metrics-host=0.0.0.0"

    ]

  besu-node4:
    image: hyperledger/besu:latest
    restart: on-failure
    container_name: besu-node4
    volumes:
      - ./data/besu-node4:/var/lib/besu
      - ./config/nodes/4/genesis.json:/var/lib/besu/genesis.json
      - ./config/nodes/4/permissions_config.toml:/var/lib/besu/permissions_config.toml
      - ./config/nodes/4/key:/var/lib/besu/key
    networks:
      - besu-network
    ports:
      - "8548:8548"
      - "9548:9548"
      - "30306:30306"
    command: [
      
      # Must parameters
      "--identity=besu-node4",
      "--data-path=/var/lib/besu",
      "--genesis-file=/var/lib/besu/genesis.json",

      # P2P
      "--p2p-port=30306", # 30303 + 3

      # Permissioned network parameters
      "--permissions-nodes-config-file-enabled",
      "--permissions-accounts-config-file-enabled",

      # RPC protocol for requests
      "--rpc-http-enabled",
      "--rpc-http-api=ADMIN,ETH,NET,PERM,IBFT",
      "--host-allowlist=\"*\"",
      "--rpc-http-cors-origins=\"*\"",
      "--rpc-http-port=8548", # 8545 + 3

      # Metrics
      "--metrics-enabled=true",
      "--metrics-port=9548", # 9545 + 3
      "--metrics-host=0.0.0.0"

    ]

  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - besu-network
    depends_on:
      - besu-node1
      - besu-node2
      - besu-node3
      - besu-node4

networks:
  besu-network:
    driver: bridge